// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rldrqubkpaxnxvlktlef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsZHJxdWJrcGF4bnh2bGt0bGVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTkwODgsImV4cCI6MjA1OTc3NTA4OH0.fggs3DLG8YVgSaJ8AE5Opg-7S8uPJoo4YGd-_yq2X68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);